### ISSUE TITLE
typo in README or bug in code

### ISSUE THREAD

**Issue by meihuisu** [NIST-ISG/OpenSeadragonFiltering#1]
I have included the filtering into my test viewer and my viewer has just 1 tiledimage
and only way to make the filter to work is to add it like this,
   myViewer.setFilterOptions({
    filters: {
        items: myViewer.world.getItemAt(1),
        processors: [ OpenSeadragon.Filters.INVERT() ]
    }
   });
note the comma after the first term in filters and also the index of 1 instead of 0.

**Comment by avandecreme** [comment]
Hi @meihuisu 

The missing coma is indeed a typo, thanks for reporting.

Regarding the index, I am not sure what is going on. Are you sure you do not have 2 items on top of each other with the one on top hiding the other entirely?
This could happen if you open OpenSeadragon with an array of tileSources without setting `sequenceMode = true` like this:

``` javascript
var viewer = OpenSeadragon({
    tileSources: [tileSource1, tileSource2]
});
```

Anyway, if you have only 1 tileSource, you can also just remove the `items` line:

``` javascript
myViewer.setFilterOptions({
    filters: {
        processors: [ OpenSeadragon.Filters.INVERT() ]
    }
});
```

**Comment by meihuisu** [comment]
My viewer will have multiple tileSources and would want to filter each tile source differently. 
I have hooked in the filter plugin but I am  not having success in verifying its working. I have 
not enable the sequenceMode. I am adding each tileSource individually with addTiledImage(). 
Right now I am seeing setting the items line in the filters seems to affect different item than the
one that the index is set to.  Do you have a working example with multi tile sources and example
on how to add and reset the filter options for different items?

**Comment by meihuisu** [comment]
I have figure out the problem, it should really be 

myViewer.setFilterOptions({
    filters: {
      items:  [ myViewer.world.getItemAt(itemID) ],
      processors: [ OpenSeadragon.Filters.INVERT() ]
   }
});

**Comment by avandecreme** [comment]
Ho yes you are right.
I thought I allowed passing a single element. This is not the case.
I am re-opening the issue to allow that.
In the meantime, I will update the doc.

Sorry about that and thanks for pointing that out.
