### ISSUE TITLE
BRIGHTNESS filter pixel need to be capped ?

### ISSUE THREAD

**Issue by meihuisu** [NIST-ISG/OpenSeadragonFiltering#3]
Should the pixel be capped within valid range after the add operation?

**Comment by avandecreme** [comment]
It should be done automatically because the canvas is using a [Uint8ClampedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray)

Are you experiencing any issue?

**Comment by meihuisu** [comment]
I was just tracing the code. Thanks.

**Comment by avandecreme** [comment]
Alright :)
