### ISSUE TITLE
When to add filtering?

### ISSUE THREAD

**Issue by meihuisu** [NIST-ISG/OpenSeadragonFiltering#4]
I have 3 greyscale images that are  layered using openseadragon's addTiledImage() call. They are being
filtered to include hue/contrast/opacity. I want the display to start with filtered stated (with color)
and I am finding a race between the tile  being available  after addTiledImage call  and when I 
am trying to add filter to the the filterlist. I am calling the add filter  within window.onload.

**Comment by avandecreme** [comment]
You should wait for the `add-item` event in the world class:

```
viewer.world.addHandler('add-item', function() {
   viewer.setFilterOptions(...);
});
```

**Comment by meihuisu** [comment]
That worked. I had to test  for  when number of
items is  the same as the number of layers that was added in order to add
all the filters only once.
