### ISSUE TITLE
Is it possible to add a filter to part of image?

### ISSUE THREAD

**Issue by SuneRadich** [NIST-ISG/OpenSeadragonFiltering#5]
I am currently working on an openseadragon implementation using single images as tiled source. I am working on adding a selection / overlay, that zooms the view. At the same time I want to dim/blur the image, except in the selected area.

Is this possible, or can you only add a filter to the entire image?

**Comment by avandecreme** [comment]
Not supported at the moment but that sounds feasible.
Would you be up to make such a patch?

**Comment by avandecreme** [comment]
Because we are moving this repository, I created a new issue for this there: https://github.com/usnistgov/OpenSeadragonFiltering/issues/1
