### ISSUE TITLE
cross-origin error

### ISSUE THREAD

**Issue by devjrowell** [NIST-ISG/OpenSeadragonFiltering#6]
When I try to use the filtering plugin I get the following error:

Unable to get image data from canvas because the canvas has been tainted by cross-origin data.

My images are hosted on a server other than where my application is hosted.  Is there a work around?  I notice that you have crossOriginPolicy: 'Anonymous' in your viewer setup.  I tried that as well but get the same error.  

Let me know if there is anything I can do to get around this.  I know I can use an ugly proxy solution but I'm hoping for something better.

Jon

**Comment by avandecreme** [comment]
> My images are hosted on a server other than where my application is hosted

You will need to add the [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) on the server hosting the images.
You can check whether this is the case in the developer console, network tab. Click on a tab which loaded with code 200 and look if there is the `Access-Control-Allow-Origin` header:

![screenshot_20160224_091826](https://cloud.githubusercontent.com/assets/465389/13287952/a07e858a-dad7-11e5-99f8-17ad667f3daf.png)

**Comment by devjrowell** [comment]
Thanx.  The header wasn't there but I added it and now everything is working.

Jon
